name: Deploy Lambda Function on AWS

on:
  push:
    branches:
      - prod-lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws-marcelo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -X clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda-jar
        path: target/fastfood-0.0.1-SNAPSHOT.jar

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name lambda-cognito-java-11 \
          --zip-file fileb://target/fastfood-0.0.1-SNAPSHOT.jar
