name: Deploy Lambda Function on AWS

on:
  push:
    branches:
      - prod-lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws-marcelo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda-jar
        path: target/fastfood-0.0.1-SNAPSHOT-shaded.jar

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        function-name: lambda-cognito-java-11  # Nome da func na AWS
        region: us-east-1
        zip-file: target/fastfood-0.0.1-SNAPSHOT-shaded.jar
